export default {
    LOAD_LABTESTS_SUCCESS: "LOAD_LABTESTS_SUCCESS",
    CREATE_LABTESTS_SUCCESS: 'CREATE_LABTESTS_SUCCESS',
    UPDATE_LABTESTS_SUCCESS: 'UPDATE_LABTESTS_SUCCESS',
    DELETE_LABTESTS_SUCCESS: 'DELETE_LABTESTS_SUCCESS',

    LOAD_DIAGNOSTICCENTER_SUCCESS: "LOAD_DIAGNOSTICCENTER_SUCCESS",

    LOAD_HOMEREMEDIES_SUCCESS:"LOAD_HOMEREMEDIES_SUCCESS",


    API_CALL: 'http://localhost:5002/'
}; 